### ISSUE TITLE
iOS no build...

### ISSUE THREAD

**Issue by santiihoyos** [AreaSeys-Team/areaseys-flutter-pdfscanner#1]
REnames brokes 

    /Users/mrmar/Development/Flutter/appcontratas/ios/Runner/GeneratedPluginRegistrant.m:18:9: fatal error: 'pdfscanner/ImagePdfScannerPlugin.h' file not found
    #import <pdfscanner/ImagePdfScannerPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by AreaSeys** [comment]
Fixed
